### ISSUE TITLE
create text files for the HP-41

### ISSUE THREAD

**Issue by bug400** [isene/hp-41cl_update#2]
I discovered recently that the HP-41 needs additional implementation bytes with the allocated file size in the implementation bytes of the LIF header. See the documentation of the updated "textlif" utility in the just released final 1.7.7 release. Without the "-r" parameter I got HEPAX file system corruptions when loading the file into HEPAX memory. Try to use the "-r 0" parameter.

**Comment by isene** [comment]
Fixed.
